import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      "Schedule Jobs": "Schedule Jobs",
      "Save Schedule": "Save Schedule",
      "Delete Schedule": "Delete Schedule",
      "Close": "Close",
      "Unassigned Jobs": "Unassigned Jobs",
      "Old or Completed Jobs": "Old or Completed Jobs",
      "Select Job": "Select Job",
      "Select Time": "Select Time",
      "Add notes": "Add notes",
      "Add task": "Add task",
      "Summary": "Summary",
      "Notes": "Notes",
      "Tasks": "Tasks",
      "Status": "Status",
      "Estimated Cost": "Estimated Cost",
      "Service Type": "Service Type",
      "Date": "Date",
      "Time": "Time",
      "Temperature": "Temperature",
      "Weather": "Weather",
      "Rain": "Rain",
      "Snow": "Snow",
      "Wind": "Wind",
      "Weather Details for": "Weather Details for",
      "Show Weather": "Show Weather",
      "Confirm": "Confirm",
      "Cancel": "Cancel",
      "Are you sure you want to delete this job?": "Are you sure you want to delete this job?",
      "Scheduled Dates": "Scheduled Dates",
      "Scheduled Date": "Scheduled Date",
      "No weather data available.": "No weather data available.",
      "Summary of Scheduled Jobs": "Summary of Scheduled Jobs",
      "Nearest Date": "Nearest Date",
      "Farthest Date": "Farthest Date",
      "This Week": "This Week",
      "This Month": "This Month",
      "Next Month": "Next Month",
      "All": "All",
      "Filter by city": "Filter by city",
      "Confirm Deletion": "Confirm Deletion",
      "Morning": "Morning",
      "Noon": "Noon",
      "Evening": "Evening",
      "Whole Day": "Whole Day",
      "Monday": "Monday",
      "Tuesday": "Tuesday",
      "Wednesday": "Wednesday",
      "Thursday": "Thursday",
      "Friday": "Friday",
      "Saturday": "Saturday",
      "Sunday": "Sunday",
      "Job Pending": "Job Pending",
      "Job Waiting": "Job Waiting",
      "Job In Progress": "Job In Progress",
      "Job Completed": "Job Completed",
      "Past Jobs": "Past Jobs",
      "To be done": "To be done",
      "Completed": "Completed",
      "Cancelled": "Cancelled",
      "Schedule for": "Schedule for",
      "Select Job": "Select Job",
      "Select Time": "Select Time",
      "Add notes": "Add notes",
      "Add task": "Add task",
      "Add Task": "Add Task",
      "To be done": "To be done",
      "Completed": "Completed",
      "Cancelled": "Cancelled",
      "Save Schedule": "Save Schedule",
      "Delete Schedule": "Delete Schedule",
      "Close": "Close",
      "Morning": "Morning",
      "Noon": "Noon",
      "Evening": "Evening",
      "Whole Day": "Whole Day"
    }
  },
  pa: {
    translation: {
      "Schedule Jobs": "ਅਜਮਾਲਤੀਆਂ ਦੀ ਅਨੁਸੂਚੀ ਬਣਾਓ",
      "Save Schedule": "ਅਨੁਸੂਚੀ ਸੰਭਾਲੋ",
      "Delete Schedule": "ਅਨੁਸੂਚੀ ਮਿਟਾਓ",
      "Close": "ਬੰਦ ਕਰੋ",
      "Unassigned Jobs": "ਅਨੁਸੂਚਿਤ ਅਜਮਾਲਤੀਆਂ",
      "Old or Completed Jobs": "ਪੁਰਾਣੀਆਂ ਜਾਂ ਪੂਰੀਆਂ ਹੋਈਆਂ ਅਜਮਾਲਤੀਆਂ",
      "Select Job": "ਅਜਮਾਲਤੀ ਚੁਣੋ",
      "Select Time": "ਸਮਾਂ ਚੁਣੋ",
      "Add notes": "ਨੋਟਸ ਜੋੜੋ",
      "Add task": "ਟਾਸਕ ਜੋੜੋ",
      "Summary": "ਸਾਰ",
      "Notes": "ਨੋਟਸ",
      "Tasks": "ਟਾਸਕਸ",
      "Status": "ਸਥਿਤੀ",
      "Estimated Cost": "ਅਨੁਮਾਨਤ ਲਾਗਤ",
      "Service Type": "ਸੇਵਾ ਦੀ ਕਿਸਮ",
      "Date": "ਮਿਤੀ",
      "Time": "ਸਮਾਂ",
      "Temperature": "ਤਾਪਮਾਨ",
      "Weather": "ਮੌਸਮ",
      "Rain": "ਮੀਹ",
      "Snow": "ਬਰਫ",
      "Wind": "ਪਵਨ",
      "Weather Details for": "ਲਈ ਮੌਸਮ ਦੇ ਵੇਰਵੇ",
      "Show Weather": "ਮੌਸਮ ਦਿਖਾਓ",
      "Confirm": "ਪੁਸ਼ਟੀ ਕਰੋ",
      "Cancel": "ਰੱਦ ਕਰੋ",
      "Are you sure you want to delete this job?": "ਕੀ ਤੁਸੀਂ ਇਸ ਅਜਮਾਲਤੀ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
      "Scheduled Dates": "ਅਨੁਸੂਚਿਤ ਤਾਰੀਖਾਂ",
      "Scheduled Date": "ਅਨੁਸੂਚਿਤ ਤਾਰੀਖ",
      "No weather data available.": "ਕੋਈ ਮੌਸਮ ਡੇਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
      "Summary of Scheduled Jobs": "ਅਨੁਸੂਚਿਤ ਅਜਮਾਲਤੀਆਂ ਦਾ ਸਾਰ",
      "Nearest Date": "ਸਭ ਤੋਂ ਨੇੜੀਕੀ ਤਾਰੀਖ",
      "Farthest Date": "ਸਭ ਤੋਂ ਦੂਰ ਤਾਰੀਖ",
      "This Week": "ਇਸ ਹਫ਼ਤੇ",
      "This Month": "ਇਸ ਮਹੀਨੇ",
      "Next Month": "ਅਗਲੇ ਮਹੀਨੇ",
      "All": "ਸਭ",
      "Filter by city": "ਸ਼ਹਿਰ ਦੁਆਰਾ ਛਾਨੀ ਕਰੋ",
      "Confirm Deletion": "ਮਿਟਾਓਣ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
      "Morning": "ਸਵੇਰ",
      "Noon": "ਦੁਪਹਿਰ",
      "Evening": "ਸ਼ਾਮ",
      "Whole Day": "ਸਾਰਾ ਦਿਨ",
      "Monday": "ਸੋਮਵਾਰ",
      "Tuesday": "ਮੰਗਲਵਾਰ",
      "Wednesday": "ਬੁੱਧਵਾਰ",
      "Thursday": "ਵੀਰਵਾਰ",
      "Friday": "ਸ਼ੁੱਕਰਵਾਰ",
      "Saturday": "ਸ਼ਨਿੱਚਰਵਾਰ",
      "Sunday": "ਐਤਵਾਰ",
      "Job Pending": "ਅਜਮਾਲਤੀ ਬਕਾਇਆ",
      "Job Waiting": "ਅਜਮਾਲਤੀ ਪ੍ਰਤੀਕਸ਼ਾ ਕਰ ਰਹੀ ਹੈ",
      "Job In Progress": "ਅਜਮਾਲਤੀ ਚੱਲ ਰਹੀ ਹੈ",
      "Job Completed": "ਅਜਮਾਲਤੀ ਪੂਰੀ ਹੋਈ",
      "Past Jobs": "ਪਿਛਲੇ ਅਜਮਾਲਤੀਆਂ",
      "To be done": "ਕਰਨ ਲਈ",
      "Completed": "ਪੂਰੀ ਹੋਈ",
      "Cancelled": "ਰੱਦ ਕੀਤੀ",
      "Schedule for": "ਲਈ ਅਨੁਸੂਚੀ",
      "Select Job": "ਅਜਮਾਲਤੀ ਚੁਣੋ",
      "Select Time": "ਸਮਾਂ ਚੁਣੋ",
      "Add notes": "ਨੋਟਸ ਜੋੜੋ",
      "Add task": "ਟਾਸਕ ਜੋੜੋ",
      "Add Task": "ਟਾਸਕ ਜੋੜੋ",
      "To be done": "ਕਰਨ ਲਈ",
      "Completed": "ਪੂਰੀ ਹੋਈ",
      "Cancelled": "ਰੱਦ ਕੀਤੀ",
      "Save Schedule": "ਅਨੁਸੂਚੀ ਸੰਭਾਲੋ",
      "Delete Schedule": "ਅਨੁਸੂਚੀ ਮਿਟਾਓ",
      "Close": "ਬੰਦ ਕਰੋ",
      "Morning": "ਸਵੇਰ",
      "Noon": "ਦੁਪਹਿਰ",
      "Evening": "ਸ਼ਾਮ",
      "Whole Day": "ਸਾਰਾ ਦਿਨ"
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: 'en', // default language
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
